# Generated by Django 5.0.6 on 2024-08-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0011_cine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.TimeField(null=True),
        ),
    ]
